# Generated by Django 3.1.1 on 2021-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='images',
            field=models.ManyToManyField(to='the_main_app.ImgModel'),
        ),
    ]
